### PR TITLE
Fixing them bugs

### PR DESCRIPTION
**Pull request by psivesely**

### CODE REVIEW

**Comment by parmegv** [comment]
If we first merge #2, this PR only adds https://github.com/webfp/tor-browser-crawler/pull/3/commits/7005e0743ce434f2a1895e03233096e1bba4bc53.

We just have to test it works, because it is much more cleaner! I like that :)

**Comment by parmegv** [comment]
@fowlslegs I'm trying to use your functionality. Since there is a vm.box in the Vagrantfile, shouldn't docker get installed into that VM automatically?

**Comment by mjuarezm** [comment]
a0a3230 covers the modifications of  7005e07 that can be committed to the current state. closing.

**Comment by parmegv** [comment]
@mjuarezm You didn't like https://github.com/webfp/tor-browser-crawler/commit/7005e0743ce434f2a1895e03233096e1bba4bc53#diff-5bc02cefb3ea9e27f1a6776eabd1935dR45? Nor https://github.com/webfp/tor-browser-crawler/commit/7005e0743ce434f2a1895e03233096e1bba4bc53#diff-5bc02cefb3ea9e27f1a6776eabd1935dR54 and https://github.com/webfp/tor-browser-crawler/commit/7005e0743ce434f2a1895e03233096e1bba4bc53#diff-16618e28b7030124192bbc97d1bbae39L18?

**Comment by psivesely** [comment]
What a terrible PR. I think I forgot I made this and kept adding things to the branch.

**Pull request closed without merging**
